### ISSUE TITLE
Delete crazies

### ISSUE THREAD

**Issue by steveoh** [agrc/StateCampuses#4]
SLCC Miller streetlights 
![image](https://user-images.githubusercontent.com/325813/33952809-2abe4a54-dff0-11e7-9623-67cb8ff1912d.png)

**Comment by brigsz** [comment]
SLCC Redwood has similar issues.  I have drawn a box around the actual campus, all others are trash

![redwood](https://user-images.githubusercontent.com/6306463/33952957-a349c840-dff0-11e7-8053-ba54560a6a84.png)
